var map,CountyCheck=["TPE","XBE","TAO","TCH"],markersArray,layer_=[],yearColumn=["2010","2014"],County_ID=["1W6H94WtxCUpX7rRou2gymm4VD3mt343nHw53bJkJ","1movvodwke4m91LpmOKesGkF_3AkE4FsbJIoc44cd","1haXdimDbBdk1t0PDpuDQ1TZNJO_Q3NLDRJ3w_lbF","1S3_dFPnthMlz0W3i5SYNbarsoSQ9YToi2JtHPWCb"],tableId=["1W6H94WtxCUpX7rRou2gymm4VD3mt343nHw53bJkJ","1VMKy6uAM3PTT9UhSZQTTBVzZxaEfLp5g6nyy2h6j","1zw0L4HbIz_dNFko8hxn5fUISMTfY3SbLiQzYlkkr"],infowindow=new google.maps.InfoWindow;
function initialize(){var a=new google.maps.LatLng(25.050621,121.548758);google.maps.visualRefresh=!0;var b=-1<navigator.userAgent.toLowerCase().indexOf("android")||navigator.userAgent.match(/(iPod|iPhone|iPad|BlackBerry|Windows Phone|iemobile)/);b&&document.querySelector("meta[name=viewport]").setAttribute("content","initial-scale=1.0, user-scalable=no");var d=document.getElementById("map_canvas");d.style.width=b?"100%":"auto";d.style.height=b?"100%":"600px";map=new google.maps.Map(document.getElementById("map_canvas"),
{center:a,zoom:11,panControl:!1,zoomControl:!0,zoomControlOptions:{position:google.maps.ControlPosition.LEFT_CENTER},mapTypeControl:!1});map.controls[google.maps.ControlPosition.RIGHT_TOP].push(document.getElementById("googft-legend-open"));map.controls[google.maps.ControlPosition.RIGHT_TOP].push(document.getElementById("googft-legend"));a=new google.maps.StyledMapType([{featureType:"all",elementType:"all",stylers:[{saturation:-75},{gamma:1.87},{visibility:"simplified"},{weight:.6}]}],{map:map,name:"Styled Map"});
map.mapTypes.set("map-style",a);map.setMapTypeId("map-style");Geojson();for(a=0;a<tableId.length;a++)layer_[a]=new google.maps.FusionTablesLayer({query:{select:"geometry",from:tableId[a],where:"County_NAME IN '\u53f0\u5317\u5e02'"},suppressInfoWindows:!0,map:map,styleId:2,templateId:2});google.maps.event.addListener(layer_[0],"click",function(a){infowindow?infowindow.close():infowindow=new google.maps.InfoWindow;infowindow.setContent('<div><table class="tg" align="center" style="width:280px;"><tr><th class="tg-i8ik" colspan="3">'+
a.row.County_NAME.value+'</th></tr><tr><td class="tg-hgcj">\u5340\u91cc\u540d\uff1a</td><td class="tg-s6z2" id="villige" colspan="2">'+a.row.Villige_NAME.value+'</td></tr><tr><td class="tg-hgcj">2014\u9078\u8209\u4eba\u6578\uff1a</td><td class="tg-s6z2" colspan="2">'+a.row["\u9078\u8209\u4eba\u6578"].value+'\u4eba</td></tr><tr><td class="tg-hgcj">2014\u8207\u524d\u5c46\u589e\u6e1b\uff1a</td><td class="tg-9vst" style="background-color:#0FF;font-weight:bold;font-size:16px;color:#F00">'+a.row["2014\u589e\u6e1b"].value+
'</td></tr></table></div><div class="tabs"><ul><li><a href="#Rate"><span>\u5169\u5c46\u9078\u8209\u6295\u7968\u7387\u8b8a\u5316</span></a></li></ul><div id="Rate"><table class="tg" style="width:270px;"><tr><td class="tg-bghc" style="width:50%; color:#000; background-color:#FFF">'+yearColumn[0]+'\u5e74</td><td class="tg-9bfu" style="width:50%; color:#000; background-color:#FFF">'+yearColumn[1]+'\u5e74</td></tr><tr><td class="tg-lhm3" style="width:50%;font-size:16px;">'+a.row[yearColumn[0]].value+'</td><td class="tg-lhm3" style="width:50%;font-size:16px;">'+
a.row[yearColumn[1]].value+"</td></tr></table></div></div>");infowindow.setPosition(a.latLng);infowindow.open(map);$(".tabs").tabs()});infowindow=new google.maps.InfoWindow;if(b){var e=document.getElementById("googft-legend"),c=document.getElementById("googft-legend-open"),b=document.getElementById("googft-legend-close");e.style.display="none";c.style.display="block";b.style.display="block";c.onclick=function(){e.style.display="block";c.style.display="none"};b.onclick=function(){e.style.display="none";
c.style.display="block"}}}google.maps.event.addDomListener(window,"load",initialize);var dataLength,town;
function Geojson(a){a="SELECT latitude, longitude, COUNTY_ID , County_NAME, TOWN_NAME FROM 1OUevGG1bi9g8ULlTdjvGdkRjy4kYhokkSuNZedG3 ";var b=generateWhere();b&&(a+="WHERE "+b);a=encodeURIComponent(a);b=["https://www.googleapis.com/fusiontables/v1/query"];b.push("?sql="+a);b.push("&key=AIzaSyDYnfgKBk-W_pXHjuYYSemkPFNFZhGQ-Q0");$.ajax({type:"GET",url:b.join(""),jsonpCallback:"jsonCallback",dataType:"json",success:function(a){dataLength=a.rows.length;for(var b=0;b<dataLength;b++)mapLabel=new MapLabel({minZoom:9,
text:a.rows[b][4],position:new google.maps.LatLng(a.rows[b][1],a.rows[b][0]),map:map,fontSize:16,fontColor:"#ffff00",strokeWeight:5,strokeColor:"#000000",zIndex:2,align:"center"}),mapLabel.set("position",mapLabel.position);return dataLength=a.rows.length},error:function(){alert("ERROR!!!")}})}
function codeAddress(a){var b=new google.maps.Geocoder;a=document.getElementById(a).value;b.geocode({address:a},function(a,b){b==google.maps.GeocoderStatus.OK?map.setCenter(a[0].geometry.location):alert("Geocode was not successful for the following reason: "+b)})}function filterMap(a,b,d,e){for(var c=0;3>c;c++)if(b)for(c=0;3>c;c++)a[c].getMap()||a[c].setMap(e),a[c].setOptions({query:{select:"geometry",from:d[c],where:b}});else for(c=0;3>c;c++)a[c].setMap(null)}
function clearmap(a,b){for(var d=0;d<a.length;d++)null!=a[d]&&a[d].setMap(null)}function generateWhere(){for(var a=[],b=document.getElementsByName("store"),d=0,e;e=b[d];d++)e.click&&(e=e.value.replace(/'/g,"\\'"),a.push("'"+e+"'"));b="";a.length&&(b="'County_NAME' IN ("+a.join(",")+")");return b};